GET http://localhost:5500/subscribers

###

GET http://localhost:5500/subscribers/6266dcd10518c88d2f3b8847

###

POST http://localhost:5500/subscribers
Content-Type: application/json

{
    "name": "Oriya",
    "subscribedToChannel": "bla-bla"
}

###

DELETE http://localhost:5500/subscribers/6266e0240518c88d2f3b8858

###
PATCH http://localhost:5500/subscribers/6266dd2c0518c88d2f3b884f
Content-Type: application/json

{
    "name": "Nadav"
}

###
POST http://localhost:5500/init
Content-Type: application/json

###
GET http://localhost:5500/health_check